-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT cliente_pkey PRIMARY KEY (id),
    CONSTRAINT cliente_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.detalle_venta
(
    id serial NOT NULL,
    venta_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10, 2) NOT NULL,
    CONSTRAINT detalle_venta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inventario
(
    id serial NOT NULL,
    producto_id integer NOT NULL,
    cantidad integer NOT NULL DEFAULT 0,
    cantidad_minima integer NOT NULL DEFAULT 5,
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT inventario_pkey PRIMARY KEY (id),
    CONSTRAINT inventario_producto_id_key UNIQUE (producto_id)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id serial NOT NULL,
    usuario_id integer NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT producto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.venta
(
    id serial NOT NULL,
    cliente_id integer NOT NULL,
    fecha timestamp without time zone DEFAULT now(),
    total numeric(12, 2) DEFAULT 0,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'pendiente'::character varying,
    CONSTRAINT venta_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.detalle_venta
    ADD CONSTRAINT detalle_venta_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_detalle_producto
    ON public.detalle_venta(producto_id);


ALTER TABLE IF EXISTS public.detalle_venta
    ADD CONSTRAINT detalle_venta_venta_id_fkey FOREIGN KEY (venta_id)
    REFERENCES public.venta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_detalle_venta
    ON public.detalle_venta(venta_id);


ALTER TABLE IF EXISTS public.inventario
    ADD CONSTRAINT inventario_producto_id_fkey FOREIGN KEY (producto_id)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS inventario_producto_id_key
    ON public.inventario(producto_id);


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT producto_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_producto_usuario
    ON public.producto(usuario_id);


ALTER TABLE IF EXISTS public.venta
    ADD CONSTRAINT venta_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.cliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_venta_cliente
    ON public.venta(cliente_id);

END;